# -*- coding: utf-8 -*-
"""mlp_test_training

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tZIxaW2GovciCffAtS69aZ4nS1vzq1EE
"""

from sklearn.metrics import precision_score, recall_score, f1_score
from stage_2_code.Method_MLP_deep import MLP
from stage_2_code.Dataset_Loader import MNISTDataset
from torch.utils.data import DataLoader
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

# =========================
# Setting
# =========================
np.random.seed(2)
torch.manual_seed(2)

train_path = "C:/Users/PC/Downloads/stage_2_data (3)/stage_2_data/train.csv"
test_path = "C:/Users/PC/Downloads/stage_2_data (3)/stage_2_data/test.csv"

batch_size = 64
learning_rate = 0.001
num_epochs = 200

# =========================
# Load Dataset
# =========================
train_dataset = MNISTDataset(train_path)
test_dataset = MNISTDataset(test_path)

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

print("Train dataset size:", len(train_dataset))
print("Test dataset size:", len(test_dataset))

# =========================
# Model / Loss / Optimizer
# =========================
model = MLP()
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# =========================
# Training
# =========================
train_losses = []

for epoch in range(num_epochs):
    model.train()
    total_loss = 0.0

    for X_batch, y_batch in train_loader:
        optimizer.zero_grad()

        outputs = model(X_batch)
        loss = criterion(outputs, y_batch)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    train_losses.append(total_loss)
    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

# =========================
# Evaluation Function
# =========================
def evaluate_model(model, data_loader, dataset_name):
    model.eval()

    correct = 0
    total = 0
    all_preds = []
    all_labels = []

    with torch.no_grad():
        for X_batch, y_batch in data_loader:
            outputs = model(X_batch)
            _, predicted = torch.max(outputs, 1)

            total += y_batch.size(0)
            correct += (predicted == y_batch).sum().item()

            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(y_batch.cpu().numpy())

    accuracy = 100 * correct / total
    precision = precision_score(all_labels, all_preds, average='weighted')
    recall = recall_score(all_labels, all_preds, average='weighted')
    f1 = f1_score(all_labels, all_preds, average='weighted')

    print(f"\n{dataset_name} Performance:")
    print(f"Accuracy: {accuracy:.2f}%")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1-score: {f1:.4f}")

    return accuracy, precision, recall, f1

# =========================
# Evaluate on Training Set
# =========================
train_accuracy, train_precision, train_recall, train_f1 = evaluate_model(model, train_loader, "Training Set")

# =========================
# Evaluate on Test Set
# =========================
test_accuracy, test_precision, test_recall, test_f1 = evaluate_model(model, test_loader, "Test Set")

# =========================
# Plot Loss Curve
# =========================
plt.plot(range(1, num_epochs + 1), train_losses)
plt.xlabel("Epoch")
plt.ylabel("Training Loss")
plt.title("Training Loss Curve")
plt.savefig("loss_curve.png")
plt.show()
